"""add all model in invoices

Revision ID: 21512332b203
Revises: 17dbbd1fe84d
Create Date: 2023-12-14 15:49:24.265758

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21512332b203"
down_revision: Union[str, None] = "17dbbd1fe84d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices_invoiceItem", sa.Column("invoice_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "invoices_invoiceItem", sa.Column("product_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_invoices_invoiceItem_product_id_products_product"),
        "invoices_invoiceItem",
        "products_product",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_invoices_invoiceItem_invoice_id_invoices_invoice"),
        "invoices_invoiceItem",
        "invoices_invoice",
        ["invoice_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(op.f("uq_users_address_id"), "users_address", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_address_id"), "users_address", type_="unique")
    op.drop_constraint(
        op.f("fk_invoices_invoiceItem_invoice_id_invoices_invoice"),
        "invoices_invoiceItem",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_invoices_invoiceItem_product_id_products_product"),
        "invoices_invoiceItem",
        type_="foreignkey",
    )
    op.drop_column("invoices_invoiceItem", "product_id")
    op.drop_column("invoices_invoiceItem", "invoice_id")
    # ### end Alembic commands ###
