"""add all model in invoices

Revision ID: 28ae8e497a15
Revises: 21512332b203
Create Date: 2023-12-14 15:49:46.165985

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28ae8e497a15"
down_revision: Union[str, None] = "21512332b203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices_invoice", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_invoices_invoice_user_id_users_user"),
        "invoices_invoice",
        "users_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_invoices_invoice_user_id_users_user"),
        "invoices_invoice",
        type_="foreignkey",
    )
    op.drop_column("invoices_invoice", "user_id")
    # ### end Alembic commands ###
