"""add other field

Revision ID: 8772008eca36
Revises: 78da9bec5746
Create Date: 2023-12-13 12:32:58.619080

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8772008eca36"
down_revision: Union[str, None] = "78da9bec5746"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("invoices", sa.Column("price", sa.Float(), nullable=False))
    op.create_unique_constraint(op.f("uq_invoices_id"), "invoices", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_invoices_id"), "invoices", type_="unique")
    op.drop_column("invoices", "price")
    op.drop_column("invoices", "name")
    # ### end Alembic commands ###
