"""add field absolute_id to all model in invoices

Revision ID: 999f605577ec
Revises: 28ae8e497a15
Create Date: 2023-12-14 17:01:31.879560

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "999f605577ec"
down_revision: Union[str, None] = "28ae8e497a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices_invoice",
        sa.Column(
            "absolute_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
    )
    op.add_column("invoices_invoice", sa.Column("address_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_invoices_invoice_address_id_users_address"),
        "invoices_invoice",
        "users_address",
        ["address_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "invoices_invoiceItem",
        sa.Column(
            "absolute_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
    )
    op.add_column(
        "products_product",
        sa.Column(
            "absolute_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
    )
    op.add_column(
        "users_address",
        sa.Column(
            "absolute_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
    )
    op.add_column(
        "users_user",
        sa.Column(
            "absolute_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_user", "absolute_id")
    op.drop_column("users_address", "absolute_id")
    op.drop_column("products_product", "absolute_id")
    op.drop_column("invoices_invoiceItem", "absolute_id")
    op.drop_constraint(
        op.f("fk_invoices_invoice_address_id_users_address"),
        "invoices_invoice",
        type_="foreignkey",
    )
    op.drop_column("invoices_invoice", "address_id")
    op.drop_column("invoices_invoice", "absolute_id")
    # ### end Alembic commands ###
