version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: ${DEV_RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${DEV_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${DEV_RABBITMQ_DEFAULT_PASS}
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"
      - "5672:5672"
