version: "3.5"

services:
  pgdb_service:
    image: postgres:14-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
    container_name: postgres
